### ISSUE TITLE
the rsnapshot command line combine not correct

### ISSUE THREAD

**Issue by jiming** [osiell/ansible-rsnapshot-master#6]
/usr/bin/rsync -a --delete --numeric-ids --relative --delete-excluded \
    --rsh=/usr/bin/ssh -i /root/.ssh/id_rsa \
    --link-dest=/var/cache/rsnapshot/hourly.1/remote_2/ \
    jiming@192.168.33.12:/home/jiming \
    /var/cache/rsnapshot/hourly.0/remote_2/ 

should be 

/usr/bin/rsync -a --delete --numeric-ids --relative --delete-excluded \
    --rsh='/usr/bin/ssh -i /root/.ssh/id_rsa' \
    --link-dest=/var/cache/rsnapshot/hourly.1/remote_2/ \
    jiming@192.168.33.12:/home/jiming \
    /var/cache/rsnapshot/hourly.0/remote_2/

**Comment by sebalix** [comment]
Hi,

Can you open a PR please?

**Comment by jiming** [comment]
This is a bug of rsnapshot, you can search '--rsh' in rsnapshot and find the line. 

I submit a bug for rsnapshot. It's not your bug.

Thanks!

Jiming

**Comment by sebalix** [comment]
Ok, thank you!
