### ISSUE TITLE
PR proposal healthcheck monitoring

### ISSUE THREAD

**Issue by mickaelperrin** [osiell/ansible-rsnapshot-master#8]
Hi,

I plan to implement an healthcheck monitoring using the https://healthchecks.io API, if the healthchecks API key is provided in configuration.

This will be simple curl requests added with `&&` to the crontab, for example:

```
/usr/bin/rsnapshot 4h &&  curl -fsS --retry 3 https://hc-ping.com/uuid-uuid-uuid > /dev/null
```

Is it something you might be interested in and you might merge ?

Regards,

**Comment by sebalix** [comment]
@mickaelperrin hi, sorry I'll not maintain this repository anymore... feel free to fork it if you want.

**Comment by mickaelperrin** [comment]
@sebalix No problem. That's how open source works. Thanks for sharing your work, it was really helpful.
